# APIs -> Application Programming Interface
# SOAP: Focus on strict and formal API design + Enterprise application.
# REST: Focus on simplicity & scalability + Most common API architecture.
# GraphQL: Focus on flexibility + Optimized for performance.

# urllib vs requests
'''
URLLIB
from urllib.request import urlopen
api = "http://api.music-catalog.com/"
with urlopen(api) as response:
    data = response.read()  
    string = data.decode()
    print(string)
'''
'''
REQUESTS
import requests
api = "http://api.music-catalog.com/"
response = requests.get(api)
print(response.text)
'''

# GET -> Read: Check the mailbox contents.
# POST -> Create: Drop a new package in the mailbox.
# PUT -> Update: Replace all packages with a new one.
# DELETE -> Delete: Remove all packages from the mailbox.
'''
GET = Retrieve a resourceresponse = requests.get('http://350.5th-ave.com/unit/243')
POST = Create a resourceresponse = requests.post('http://350.5th-ave.com/unit/243', data={"key": "value"})
PUT = Update an existing resourceresponse = requests.put('http://350.5th-ave.com/unit/243', data={"key": "value"})
DELETE = Remove a resourceresponse = requests.delete('http://350.5th-ave.com/unit/243')
'''

import requests

# Create query params to get API specifics.
query_params = {'artist': 'Deep Purple', 'include_track' : True}

response = requests.get('http://localhost:3000/lyrics/random', params=query_params)

# Print the response URL
#print(response.url)
# Print the lyric
#print(response.text)

'''
http://localhost:3000/lyrics/random?artist=Deep+Purple&include_track=True
Come on, come on, come on. Let's go space truckin' - Deep Purple, Space Truckin
'''

# Status Codes
# 1XX -> Informational responses.
# 2XX -> Successful responses.
# 3XX -> Redirection message.
# 4XX -> Client error responses.
# 5XX -> Server error responses.
# Most common -> 200 OK - 404 Not Found - 500 Internal Server Error

response = requests.get('http://localhost:3000/movies')

# Check if the response.status_code is equal to the requests.codes value for "200 OK"
if (response.status_code == requests.codes.ok):
    print('The server responded succesfully!')
  
# Or if the request was not successful because the API did not exist, 404
elif (response.status_code == requests.codes.not_found):
    print('Oops, that API could not be found!')

###################################
# Add a header to use in the request
headers = {'accept': 'application/xml'}
response = requests.get('http://localhost:3000/lyrics', headers=headers)

# Check if the server did not accept the request
if (response.status_code  == requests.codes.not_acceptable):
    print('The server can not respond in XML')
    
    # Print the accepted content types
    print('These are the content types the server accepts: ' + response.headers['accept'])
else:
    print(response.text)

'''
The server can not respond in XML
These are the content types the server accepts: application/json, text/plain
'''

# Authentication
print("*****Authentication*****")
# Basic Authentication: The simplest technique for enforcing access controls to web resources because 
# it doesn't require cookies, session identifiers, or login pages. Basic authentication transmits credentials as user ID/password pairs, encoded using Base64.

# Create a tuple of your username and password
authentication = ('john@doe.com','Warp_ExtrapolationsForfeited2')

# Make a GET request with basic authentication
response = requests.get('http://localhost:3000/albums', auth=authentication)

if(response.status_code == 200):
    print("Success!")
elif(response.status_code == 401):
    print('Authentication failed')
else:
    print('Another error occurred')

# API Key/ Token Authentication: A token is a unique string of characters that is generated by the server in response to a login request. 
# The client must send this token in the header of subsequent requests to access protected resources.

# Create a dictionary containing the API key using the correct key-value combination
params = {'access_token': '8apDFHaNJMxy8Kt818aa6b4a0ed0514b5d3'}
# Add the dictionary to the requests.get() call using the correct function argument
response = requests.get('http://localhost:3000/albums', params=params)

if(response.status_code == 200):
    print("Success!")
elif(response.status_code == 401):
    print('Authentication failed')
else:
    print('Another error occurred')

# Using headers to send the token is more secure than using query parameters.
# Create a headers dictionary containing and set the API key using the correct key and value 
headers = {'Authorization': 'Bearer 8apDFHaNJMxy8Kt818aa6b4a0ed0514b5d3'}
# Add the headers dictionary to the requests.get() call using the correct function argument
response = requests.get('http://localhost:3000/albums', headers=headers)

if(response.status_code == 200):
    print("Success!")
elif(response.status_code == 401):
    print('Authentication failed')
else:
    print('Another error occurred')

# JSON APIs.
print("*****JSON APIs*****")

# Create a variable called API_TOKEN and set it equal to the API token string
headers = {
    'Authorization': 'Bearer ' + API_TOKEN,
    # Add a header to request JSON formatted data
    'accept': 'application/json'
}
response = requests.get('http://localhost:3000/albums/1/', headers=headers)

# Get the JSON data as a Python object from the response object
album = response.json()

# Print the album title
print(album['Title'])

###############################
# Create a list of dictionaries called playlists, where each dictionary contains a key-value pair for the name of the playlist.
playlists = [{"Name":"Rock ballads"}, {"Name":"My favorite songs"}, {"Name":"Road Trip"}]

# Make a POST request to the API endpoint to create the playlists, passing in the playlists list as JSON data
requests.post('http://localhost:3000/playlists/', json=playlists)

# Make a GET request to the API endpoint to retrieve the playlists
response = requests.get('http://localhost:3000/playlists')

# Print the response text to see the playlists that were created
print(response.text)
# [{"PlaylistId":1,"Name":"Classical music"},{"PlaylistId":2,"Name":"Pop"},{"PlaylistId":3,"Name":"Rock ballads"},{"PlaylistId":4,"Name":"My favorite songs"},{"PlaylistId":5,"Name":"Road Trip"}]

# Error handling
print("*****Error handling*****")

# Import the correct exception class
from requests.exceptions import ConnectionError, HTTPError

url ="http://localhost:3000/albums/"
try: 
    r = requests.get(url) 
	# Enable raising errors for all error status_codes
    r.raise_for_status()
    print(r.status_code)
except ConnectionError as conn_err: 
    print(f'Connection Error! {conn_err}.')
# Intercept the error 
except HTTPError as http_err:
    print(f'HTTP error occurred: {http_err}')